- name: Deploy WordPress to WP Engine
  # You may pin to the exact commit or the version.
  # uses: wpengine/github-action-wpe-site-deploy@a5c4a5c651162b7085b8be46b2cfe15308d15bdc
  uses: wpengine/github-action-wpe-site-deploy@v2.3.3
  with:
    # The private RSA key you will save in the Github Secrets
    WPE_SSHG_KEY_PRIVATE: 
    # optional php syntax check
    PHP_LINT: # optional
    # Optional flags for the deployment
    FLAGS: # default is -azvr --inplace --exclude=".*"
    # Optional WPE Clear cache
    CACHE_CLEAR: # optional, default is true
    # An optional source directory to deploy other than the root directory that is being versioned.
    TPO_SRC_PATH: # optional, default is .
    # An optional destination directory to deploy to other than the WordPress root.
    TPO_PATH: # optional, default is 
    # Source branch to deploy PRD_ENV
    PRD_BRANCH: # default is PROD_BRANCH_HERE
    # Destination to deploy to WPE Prod
    PRD_ENV: # default is PROD_ENV_HERE
    # Source branch to deploy STG_ENV
    STG_BRANCH: # optional, default is STAGE_BRANCH_HERE
    # Destination to deploy to WPE Stage
    STG_ENV: # optional, default is STAGE_ENV_HERE
    # Source branch to deploy DEV_ENV
    DEV_BRANCH: # optional, default is DEV_BRANCH_HERE
    # Destination to deploy to WPE Dev
    DEV_ENV: # optional, default is DEV_ENV_HERE
