name: Deploy to WP Engine
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-plugin:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy Plugin
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete
        CACHE_CLEAR: TRUE
        TPO_SRC_PATH: "wp-content/plugins/"
        TPO_PATH: "wp-content/plugins/"      
        DEV_BRANCH: main
        DEV_ENV: bosleydevelop
  deploy-theme:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy Theme
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete
        CACHE_CLEAR: TRUE
        TPO_SRC_PATH: "wp-content/themes/twentytwentyone/"
        TPO_PATH: "wp-content/themes/twentytwentyone/"      
        DEV_BRANCH: main
        DEV_ENV: bosleydevelop
